In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

# load dataset
data = pd.read_csv("/content/Iris.csv")

In [3]:
# features and target
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)



In [4]:
# Naive Bayes
model = GaussianNB()
model.fit(X_train, y_train)

# prediction
y_pred = model.predict(X_test)

# confusion matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
